### ISSUE TITLE
Do you have script for mac and windows

### ISSUE THREAD

**Issue by blaremc** [butterproject/nwjs-build#1]
Hello! Great work! Do you have scripts like this but for nw18 for windows and mac?

**Comment by vankasteelj** [comment]
No, it doesn't work properly anyways

**Comment by blaremc** [comment]
@vankasteelj Thanks for answer. I mean script which can build mac and windows version. You have all builds here http://builds.butterproject.org/nw/v0.18.6/  How did you build mac and windows version?

**Comment by vankasteelj** [comment]
It wasn't me, I have absolutely no idea what kind of black magic is happening over there. @xaiki might tell you more.

**Comment by xaiki** [comment]
we actually mirror them from popcorntime.sh, they build nw with a lot of fiddeling and manual intervention every time
sorry no easy answer.

**Comment by vankasteelj** [comment]
If https://github.com/nwjs/nw.js/issues/5653 ever gets through, we might be able to simply peer that with https://github.com/iteufel/nwjs-ffmpeg-prebuilt (might need some tweaks but the biggest is there)

**Comment by blaremc** [comment]
Thanks for help. I've found they builds here https://get.popcorntime.sh/repo/nw/
Btw neither 18.6 nor 18.8 doesn't play avi on Windows, so i think use wcjs instead of.

**Comment by vankasteelj** [comment]
WCJS is dead, sadly (because lib support on 3.0 will be near impossible to hack), plus it doesnt read avi well either, due to an avi patch that the vlc team doesnt want to merge. 

And nwjs probably will never be able to read avi correctly due to being based on chromium, and Google doesn't want avi support, and chromium team doesnt seem to see an interrest in it. 

It's sad, but due to "big players" having a closed view on file formats, plus most of them being in the US where the laws regarding codecs are, how to put it respectfully, horrible, well... we might as well stop trying to make avi file work... That's where I stand at this point.
